import os
import sys

def q4():
    print("Wil je dit programma opnieuw starten? (y / n)")
    dontclose = input()
    if(dontclose == "y"):
        os.execl(sys.executable, '"{}"'.format(sys.executable), *sys.argv)
    elif(dontclose == "n"):
        sys.exit()
    else:
        print("Typ alstublieft 'y' of 'n' in.")

def q1():
    print("We moeten vluchten! We hebben geprobeerd hier zo lang mogelijk te blijven maar ze blijven maar komen. Meer explosies elke dag en nacht! Dat is het enige waar ik aan kon denken terwijl ik en mijn zus Amira vluchten voor de geluiden van oorlog. Tot weinig verbazing waren wij niet de enige van plan om te vluchten, iedereen was in paniek. Mensen liepen zelfs over elkaar heen om sneller in veiligheid te komen. Terwijl we proberen te vluchten houden we elkaars handen goed vast zodat we elkaar niet verliezen in de massa. We kunnen nog steeds de explosies en kogel schoten horen vanaf hier. Mijn zus en ik zijn al buiten de risico zone, maar onze ouders zijn nog niet gekomen, zou ik terug gaan naar ons huis om te kijken?")
    print("")
    print("A: Ga terug om je ouders te halen")
    print("B: Ren weg met je zus nu")
    a1 = input(" Kies 'A' of 'B' >>>>> ")
    if (a1 == "A"):
        print("")
        print("Je vertelde tegen je zus dat je gaat proberen om jullie ouders te zoeken en mee te brengen. Ze protesteert er tegen maar je gaat toch. Terwijl je rent door de half afgebroken huizen zie en hoor je meerdere explosies om je heen maar tot nu toe nog geen mensen met wapens, alleen lijken.")
        print("Je haalde het thuis maar het was al te laat, je ouders lagen met bloed op de grond en kogel schoten door hun lichaam. Je wilt huilen bij hun voor een tijdje maar je weet dat dit niet de tijd is. Dus je staat snel weel op om terug te gaan, maar tot groot ongeluk werd je vol geraakt door een explosie, een mijn… een RPG schot… maakt niet uit, je stierf daar en werd herenigd met je familie terwijl je hoopt dat je zus het red zonder je.")
        print("")
        q4()
    elif (a1 == "B"):
        print("")
        print("Je besloot om niet te terug te gaan voor je ouders, je zus knikte met jou keuze en liepen door met de massa’s. Tijdens het lopen was er een kort moment van stilte tot je zus barste in tranen, je troost haar zo veel je kan maar zelfs jij kan je tranen niet achter houden.")
        print("")
    else:
        print("")
        print("Kies alstublieft A of B")
        print("")
        q1()
q1()

def q2():
    print("We hebben alles verloren… Familie, vrienden, een thuis, en ons land. Iedereen om ons heen voelde zich even slecht als wij. Volgens een paar waren er boten verder op die ons zullen brengen naar West Europa. Mijn zus en ik geven niet om waar we heen gaan, zo lang we maar veilig zijn daar.")
    print("")
    print("Het was een lange wandeling, we realiseerden ons net dat we geen eten hebben meegenomen. Er was een moment van stilte weer en hoopte dat het goed zou komen, gelukkig hoorde één van de mensen ons, een volwassen vrouw. Nogal heeft iedereen zo veel verloren was ze nog best positief over de situatie, ze gaf ons wat eten, stelde ons gerust en glimlachte naar ons. Wij beide bedankte haar en glimlachte terug, hopelijk gaat de rest van onze reis ook zo goed.")
    print("")
    print("Dagen gingen voorbij als wij over het landschap bleven lopen. Sommige hebben al het loodje gelegd onderweg, dat was zeker weten niet iets wat iedereen een positieve kijk op de situatie geeft. Veel hebben last van hun lijf, vooral voeten van al het lopen. Amira heeft er ook last van, als oplossing heb ik lappen stof om haar voeten heen gewikkeld om te hopen dat het wat zachter voelt voor haar. Ze is erg blij er mee. Zelfs in deze zware tijden zullen we elkaar altijd behandelen als broer en zus.")
    print("")
    print("Eindelijk… we hebben het gehaald! Toen we het water bereikte zagen we boten. Ik zelf was erg opgelucht dat ze niet logen over de boten, maar Amira maakt zicht zorgen over iets anders. Toen ik het aan haar vroeg wees ze naar de boten en had haar twijfels of deze boten het zouden halen naar West Europa. Het waren boten gemaakt van rubber, en waren niet al te groot. Als iedereen mee wou dan zou het proppen moeten worden. Maar iedereen stapt gewoon in. Redelijk logisch natuurlijk dit is beter dan het risico lopen om te sterven in je slaap… als je überhaupt al slaap had kunnen krijgen met de explosies dag en nacht. Ik stelde Amira een beetje gerust, vertelde haar dat dit de enige kans is om naar een betere plek te gaan. Ze was stil voor een lange tijd, maar uiteindelijk knikt ze ja. We stappen samen in de boot en niet veel later waren we op het water. Samen met 5 andere boten vol mensen.")
    print("")
    print("Tot nu toe gaat alles nog wel soepel! Iedereen is ook een stuk meer gerust dat ze niet meer in de oorlog zone zitten, ze zijn nog wel bezorgd of ze het zullen halen maar mensen praten veel meer met elkaar. Wij waren aan het praten met die mevrouw van eerder. Haar naam was Senna, het moment toen we eenmaal onderweg waren lachte ze en zei: “Ik zei het toch! Maak je niet zo druk!”. Ik en Amira lachte mee en de rest van de mensen op de boot voelde zich ook een stuk beter.")
    print("")
    print("Dagen gingen voorbij, iedereen voelt zich nog wel redelijk goed. We spraken met een stel op de boot links van ons, ze waren recent getrouwd en moesten dagen later vluchten. Aan het eind van het gesprek wenste ze ons meer geluk met wanneer één van ons gaat trouwen. Wij wenste hun een lange relatie samen, en aan hun gesprekken te horen geloven wij wel dat ze lang gelukkig samen zullen zijn. Nu alleen nog zorgen dat we ook allemaal blijven leven.")
    print("")
    print("Meer dagen gingen voorbij… veel mensen werden ziek en sommige gingen dood door de kou of door wonden die ze hadden opgelopen toen iedereen probeerde te vluchtte. Mensen voelen zich ook een stuk minder goed. Zelfs Senna is een beetje stiller geworden, we hadden allemaal afgesproken voor dat iedereen ging slapen we allemaal zouden bidden naar de hemels. Hopen dat ze ons naar geluk zouden leiden. Het is het enige wat we kunnen doen.")
    print("")
    print("De volgende dag was er niet veel gebeurt… naast dat we de andere boten waren verloren toen we sliepen. We geloven dat ze nog leven en hopen dat ze het zullen halen. Maar zelfs al is het waarschijnlijk dat ze nog leven, voelt iedereen zich een beetje leger van binnen.")
    print("")
    print("We werden wakker midden in de nacht van een schreeuw van angst en schrik. Het was Senna, toen we onze ogen open deden keken we toe hoe een man het water in sprong en niet meer omhoog kwam. Het was Senna’s man, we probeerde haar zo veel mogelijk te troosten maar het was te veel voor haar. We bleven haar troosten tot we allemaal weer in slaap vielen.")
    print("")
    print("De volgende dag was iedereen stil. Niemand zei een woord. Maar de stilte werd gebroken met het verschrikkelijke nieuws wat niemand zou willen horen… We hadden geen drinkwater meer. Iedereen was erg verbaasd met hoe snel het allemaal weg was… maar naast wat huilen bleef iedereen stil. Niemand wist hoe ze het probleem konden oplossen.")
    print("")
    print("We wisten niet dat het hier op zou aankomen. Maar Senna kon het niet meer aan. We dachten dat zij de laatste persoon zou zijn die gek werd maar duidelijk was het verlies van haar man te veel voor haar. We probeerde haar te stoppen maar ze wilde niet meer leven in een wereld zonder haar geliefde. Amira draaide snel om en hield mij vast toen ze het water in sprong en niet meer boven water kwam. We verloren zoveel mensen. Het was hier niet veel beter dan terug in ons land, maar we kunnen niet meer terug. Dus we hopen voor het beste en varen door.")
    print("")
    print("")
    print("Je keel was zo droog… het deed pijn om te praten. Het voelt alsof je dood gaat. Je begint dingen te zien die niet zouden kloppen… land waar eerst water was… mensen waar nu legen plekken zaten… familie leden die of dood zijn of vermist zijn… Je wordt er gek van. Je zus probeert je een beetje “wakker te houden”. Het is zo warm… zo droog. Je hebt… water… nodig…")
    print("")
    print("A: Drink het zee water")
    print("B: Blijf stil zitten")
    a2 = input("Kies 'A' of 'B' >>>>> ")
    if (a2 == "A"):
        print("")
        print("Je besloot om zee water te drinken, het voelde zo goed maar je wilde meer, je zus en een paar andere probeerde je te stoppen maar je ging door. Je wilde meer, meer en meer. Het voelde alsof hoe meer je drinkt hoe meer je wilt. Maar dat maakt niet uit. Je keel voelde beter… en je had geen dorst meer! Je ging door en door tot het te erg was voor je lichaam. Zonder dat je het realiseerde werd de conditie van je lichaam slechter en slechter. Je kon amper bewegen, je zus probeerde je in leven te houden om het water uit je te duwen maar het was te laat, je ogen sloten dicht, het laatste wat je zag was je zus bezorgde gezicht en de blauwe lucht… Je hoopt dat je zus het zal halen zonder je.")
        print("")
        q4()
    elif (a2 == "B"):
        print("")
        print("Je besloot om niet zee water te drinken, Al was je compleet gek geworden maakte je de juiste keuze en besloot niet om je gekke gedachten je hoofd te laten overnemen. Al was het zwaar om door te gaan, je kwam er door heen met de hulp van je zus. God, als u mij hoort… ze is te goed voor deze wereld…")
        print("")
    else:
        print("")
        print("Kies alstublieft A of B")
        print("")
        q2()
q2()

def q3():
    print("De dagen werden zwaarder en zwaarder, en de boot werd leger en leger tot we een sprank van geluk zagen op het water. “EEN BOOT!” riep één van de mensen op de boot, we sprongen allemaal op en keken er naar tot we begonnen met zwaaien er naar. We bleven zwaaien en zwaaien en uiteindelijk zag de boot ons. “Eindelijk… het is voorbij” zei ik in een zucht. Mijn zus hield me goed vast tot de boot vlak naast ons zat, we werden aan boord gelaten en kregen eten, drinken en een deken. We wisten niet wat ze tegen elkaar zeggen tot één naar ons toe liep en onze taal sprak, hij zei: “Het is goed nu! Jullie zijn in goede handen. Jullie zijn niet de enige die het hebben gehaald.” Zo te horen heeft hij dit eerder gedaan. Werden we opgewacht? Ik had heel veel vragen maar ik besloot om ze niet te stellen. Het hoeft niet… niet nu… want we zijn nu veilig… en dat is waar het om gaat. Amira en ik zaten samen onder één deken, dicht bij elkaar. Ik wou nog tegen haar praten en haar meer gerust stellen maar toen ik naar haar keek was ze diep in slaap op mijn schouder. Het voelde zo fijn… het was een warm gevoel… en gevoel dat ik niet heb gevoelt sinds we vertrokken.")
    print("")
    print("De boot bracht ons aan land, ik en Amira hielden elkaars handen goed vast… maakt niet uit wat er gebeurt of wat we ook moeten doen… we doen het samen. We werden samen met andere bij elkaar toegevoegd in een grote zaal. We moesten daar wat over ons zelf vertellen zoals waar we vandaan kwamen. Uiteindelijk werd er aan ons verteld dat we ons bevinden in “Nederland.” Geen idee waar we precies zijn… maar we zijn veilig. Na dat iedereen zijn verhaal heeft gedeeld werden we gebracht naar een andere plek… een soort “opvang” voor vluchtelingen… Het was niet knus maar het was goed genoeg voor ons. Ze gaven ons instructies en regels die we moesten volgen voor we naar onze kamers werden gestuurd. Ik mocht samen met Amira omdat we familie waren. Morgen zullen ze ons meer vertellen. Maar voor nu… een lange rust in een zacht bed.")
    print("")
    print("In mijn slaap had ik een nachtmerrie… of meer een collage van nare herinneringen van onze reis… Mensen die dood gingen… mensen die we nooit meer terug zagen… het was zo veel… ik wou schreeuwen maar ik kon niet spreken… ik wou rennen maar ik kon niet bewegen… plotseling… werd ik wakker, zwetend als ik om mij heen keek. Ik was nog steeds hier… het was geen droom dat we het hebben gehaald. Ik zucht in opluchting en ging weer liggen. Hopelijk zal ik niet vaker dit soort nachtmerries krijgen.")
    print("")
    print("Het was ochtend. Ik en Amira werden laat wakker, maar de mensen die hier werken waren daar gewend aan geraakt zo te zien. Toen we weer in de hal waren en begonnen met ontbijten kregen we meer en meer informatie. Amira had een pen en papier gekregen van één van de medewerkers zodat ze kon opschrijven wat we moesten onthouden. Ze legde ons uit dat als je hier wil wonen dan moet je daar heel wat werk voor doen. Best lastig om allemaal te volgen maar gelukkig hield Amira het goed bij. Aan het eind vertelde ze dat we naar buiten mochten als je wil, zolang we maar terug waren voor 6 uur. Iedereen kreeg een horloge om de tijd mee bij te houden, kort daarna was het gesprek klaar en gingen ik en Amira naar buiten om de buurt te bekennen. Het leek een beetje op ons land maar veel was ook nieuw. Terwijl wij onze wandeling maakte hadden we het over wat er werd besproken tijdens het ochtend gesprek. We waren het beide eens met dat we hier willen gaan wonen. De dingen die we zagen tijdens onze wandeling gaven ons alleen meer redens om hier te blijven.")
    print("")
    print("Je denkt er over na. Alles ziet er hier zo mooi uit… Maar je hebt geen idee of het wel veilig is. Kan het allemaal soms te goed om waar te zijn? Amira is er best naïef over en is bereid om hier te blijven. Maar na alles waar je door bent gekomen heb je “trust issues” gekregen. Is het echt waar allemaal? Het is allemaal zo moeilijk. Maar je bent zeker dat je vandaag wel een besluit gaat maken, jou besluit is…")
    print("")
    print("A: Blijf in Nederland met Amira")
    print("B: Ren weg naar een andere plek")
    a3 = input("Kies 'A' of 'B' >>>>> ")
    if (a3 == "A"):
        print("")
        print("We besloten om de stappen te volgen die aan ons werd gegeven en hopelijk hier te kunnen wonen. Dagen gingen voorbij. We moesten zo veel doen om hier te kunnen wonen maar dat maakte ons niet uit. We waren vastberaden om door te gaan tot het is gelukt. Eén van de meest aparte dingen die we moesten doen was een soort quiz te maken over Nederland en ons gedrag. Sommige vragen begreep ik nog wel maar andere waren heel moeilijk. Toch met enig geluk was het ons beide gelukt om te slagen voor de test! De rest ging even succesvol en voor dat we het wisten kregen we onze Nederlandse paspoorten. We huilden tranen van geluk... Het is ons gelukt! We hebben het gehaald!")
        print("")
        print("")
        print("")
        print("-MAANDEN LATER-")
        print("")
        print("Toen ik dit dagboek weer op pakte toen voelde het alsof het gisteren was, al deze obstakels en avonturen die ik en Amira hebben beleefd. Het was zeker iets wat ik zeker een verhaal wat ik zou willen door vertellen. Ik ben nu een succesvolle medewerker in de Media Markt en mijn zus werkt nu in “accounting”. We zijn beide gelukkig met hoe het is gegaan, we hebben veel contact met elkaar en hebben veel nieuwe vrienden leren kennen in onze tijd hier. Toch kan ik het niet helpen om een beetje verdriet te voelen van de mensen die we hebben verloren. Elke keer zit ik met gedachten zoals: “Wat als DIT gebeurt was” of “Wat als ik dit had kunnen doen.” Constant nadenken over wat ik had kunnen doen om dit verhaal toch wat beter had kunnen laten eindigen. Maar zelfs dan zou het vast geen verschil maken. Amira zegt dat ik er niet zo veel over druk moet maken. Grappig, dat is wat ik tegen haar zei toen wij op de vlucht waren. Maar hoe dan ook dit verhaal eindigt. Ik bid elke dag voor iedereen… ik bid dat niemand meer een ervaring zoals deze zou moeten voelen. Niemand. Want niemand verdient het om door deze hel heen te komen. Al eindigt het goed of slecht. Tot zo ver… dit is waar mijn verhaal eindigt. Lezer, wie je ook bent… als het ooit voelt alsof het leven niet erger kan, denk aan dit verhaal… Er is altijd een manier. Altijd.")
        print("")
        print("-Georgië")
        print("")
        print("")
        print("")
        print("Einde")
        print("Druk op ENTER om programma af te sluiten.")
        dontclose2 = input()
    elif (a3 == "B"):
        print("")
        print("Je verteld Amira dat je het niet vertrouwd hier, ze begrijpt jou compleet niet. Ze ziet geen reden om weg te gaan. Toch na uren argumenteren besloot je om door te gaan met je plan. Maar helaas… Amira ging niet mee. Ze besloot om in Nederland te blijven terwijl jij vluchtte naar een andere plek.")
        print("")
        print("Elke stap die ik nam op mijn weg naar een betere plek voelde ik me meer schuldig om niet met Amira’s plan mee te gaan. Maar ik sta er nog steeds bij dat dit de beste optie is en de veiligste.")
        print("")
        print("Veel dagen later kwam ik aan in een ander land… het heet “Griekenland.” Ik weet niet veel van de landen hier maar in ieder geval accepteerde ze mij ook in hun land op dezelfde manier als Nederland dat deed. Ook daar moesten ik bepaalde dingen doen zoals rare quiz vragen om een paspoort te krijgen. Het waren best rare vragen maar met een beetje leren was ik er doorheen gekomen.")
        print("")
        print("")
        print("")
        print("-MAANDEN LATER-")
        print("")
        print("Het is al een tijdje geleden sinds ik laatst in dit dagboek heb geschreven. Er is ook veel gebeurt in de dagen tussen nu en de laatste keer dat ik had geschreven. Kort samengevat ben ik nu een burger in Griekenland. Financieel is alles best zwaar, en goed werk zoeken is ook redelijk moeilijk. Toch wat me het hardste raakte was toen ik uiteindelijk weer contact kon maken met Amira. Ze vertelde me dat alles hier goed is. Ze is nu een burger van Nederland en werkt in “accounting”. Ze vertelde me veel over wat ze daar heeft gedaan en hoe het gaat en ik deed hetzelfde. Al zijn we opgesplitst zijn we nog steeds heel erg close met elkaar. Toch nog... Vraag ik me af of het een goed idee was om weg te rennen. Mijn gedachten waren zo gefocust op blijven vluchten dat ik me nooit realiseerde dat we onze bestemming al hadden bereikt. De traumatiserende gebeurtenissen op onze reis hebben ons ook niet helemaal verlaten. We hebben er nog steeds nachtmerries over. De enige opluchting die we hebben is dat we het hebben gehaald en dat wij nu veilig zijn. Het is best moeilijk om nieuwe dingen hier te leren en oude gewoontes te laten vallen. Maar we komen er wel, dat weten we zeker. Uiteindelijk wou ik heel graag naar Nederland reizen zodat ik Amira kon zien. Zij was er ook erg enthousiast over. Maar toen gebeurde er iets waar we weinig verstand van hadden… mensen noemde het een “lockdown” vanwege een virus dat zich verspreidt over Europa. We kunnen niet naar elkaar reizen makkelijk tijdens de lockdown dus we moeten blijven waar we zitten. We zijn beide best opgelucht over dat we hier nu zijn. Wie weet hoe erg het had kunnen zijn als we nog in ons thuis land zitten zonder enig idee van deze lockdown. Toch hopen we dat andere vluchtelingen worden ingelaten tijdens de lockdown. Want niemand verdient om door deze reis heen te gaan zonder een goed einde. Niemand.")
        print("")
        print("Tijdens de lockdown worden dingen best zwaar. Maar we hebben erger gehad… en we hebben elkaar online… Dus wat er ook op ons af wordt gegooid. We zullen samen er voorbereid op zijn. Alles.")
        print("")
        print("Maar zelfs dan… Vraag ik me af of het anders had kunnen eindigen als ik niet was gevlucht… of als ik terug was gegaan voor mijn ouders. Wie weet. Ik zal het nooit weten. Maar ik hoef het ook niet te weten. Ik moet het verleden los laten en naar de toekomst kijken. Hoe moeilijk het ook kan zijn.")
        print("")
        print("-Georgië")
        print("")
        print("")
        print("")
        print("Einde")
        print("Druk op ENTER om programma af te sluiten.")
        dontclose2 = input()
    else:
        print("")
        print("Kies alstublieft A of B")
        print("")
        q3()
q3()
